Add support for more currencies
sharkdp/numbat pull request #216
Opened 2023-10-28 18:00 UTC by zaidhaan

Hey there, nice tool! I've noticed that not all the currencies from the [XML file](https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml) you guys get your exchange rate data from are used (some of which I use quite frequently), so I thought I'd add a few of the remaining ones.

Not entirely sure if this is correct, but I did some testing and it looks alright.

2023-11-02 08:58 UTC, mhmdanas requested changes
Thank you! Can you also please add the new currencies to `book/src/list-units.md`?

2023-11-02 08:58 UTC, mhmdanas commented on numbat/modules/units/currencies.nbt
> +unit philippine_peso: Money = EUR / exchange_rate("PHP")
Let's add the Saudi Riyal as well:

```
@aliases(saudi_riyals, SAR: short, SR)
unit saudi_riyal: Money = EUR / exchange_rate("SAR")
```

2023-11-02 08:58 UTC, mhmdanas commented on numbat/src/lib.rs
> +                        "₱",
```suggestion
                        "₱",
                        "saudi_riyal",
                        "saudi_riyals",
                        "SAR",
                        "SR",
```

2023-11-02 18:21 UTC, sharkdp commented
> Can you also please add the new currencies to `book/src/list-units.md`?

Yes, that would be great. I want to automate this at some point, but didn't get around to it.

2023-11-03 09:00 UTC, sharkdp commented
> I want to automate this at some point, but didn't get around to it.

Did that now in #223 and updated your PR with the corresponding information.

2023-11-03 09:01 UTC, sharkdp approved these changes

2023-11-03 09:03 UTC, sharkdp commented
Changes are live on numbat.dev: https://numbat.dev/?q=%E2%82%AC+-%3E+%E0%B8%BF%E2%8F%8E

2023-11-03 09:09 UTC, merged

2023-11-05 13:40 UTC, zaidhaan commented
Ah, thanks for completing that @sharkdp! Sorry, was a little bit busy lately and wasn't able to get to it myself