add the rest of the currency exchange rates provided by the European Central Bank
sharkdp/numbat pull request #226
Opened 2023-11-04 17:01 UTC by herlev

adds the currencies DKK, SEK, ISK, NOK, ILS and ZAR as units to numbat

2023-11-05 02:40 UTC, hotgluebanjo commented on book/src/list-units.md
> +| `Money` | [South African rand](https://en.wikipedia.org/wiki/South_African_rand) | `ZAR`, `south_african_rand` |
I believe we're supposed to auto-generate this table for consistent sorting: #223

2023-11-06 14:48 UTC, mhmdanas requested changes

2023-11-06 14:48 UTC, mhmdanas commented on numbat/modules/units/currencies.nbt
> +@aliases(icelandic_krónur, ISK: short)
Hmm, maybe it's a good idea to add aliases without any diacritics as well?

2023-11-06 18:36 UTC, sharkdp approved these changes
Thank you very much for your contribution!

2023-11-06 18:36 UTC, merged

2023-11-06 18:43 UTC, sharkdp commented
The changes are live on https://numbat.dev

https://numbat.dev/?q=100+DKK+to+EUR%E2%8F%8E

2023-11-11 20:18 UTC, sharkdp commented
And released as https://github.com/sharkdp/numbat/releases/tag/v1.8.0