fix: formatting in `numbat-wasm/www/`
sharkdp/numbat pull request #457
Opened 2024-06-05 19:51 UTC by hamirmahal

fixes #456.

2024-06-05 19:51 UTC, hamirmahal commented on numbat-wasm/www/terminal.css
We should auto-format any file we plan on editing. I'm unsure if `numbat-wasm/www/terminal.css` fits that criteria.

2024-06-23 12:00 UTC, sharkdp requested changes
I'm okay with auto-formatting `main.css`, `index.js` and `index.html`. Please revert all of the other changes, including the new files. I'd like to keep this minimal.

2024-06-24 22:56 UTC, hamirmahal commented
What're your thoughts on using https://github.com/biomejs/biome to lint and format web code?

It's written in Rust.

2024-07-01 17:42 UTC, sharkdp commented
> What're your thoughts on using https://github.com/biomejs/biome to lint and format web code?

But that's only for JavaScript, right?

2024-07-09 15:36 UTC, hamirmahal commented
> > What're your thoughts on using https://github.com/biomejs/biome to lint and format web code?
> 
> But that's only for JavaScript, right?

I'm not too sure. I haven't used it before, but I can look into it if you're interested in integrating it with `numbat-wasm/www/`.

2024-08-09 12:44 UTC, sharkdp commented
Closed via 8ce1eea5c38f7f52661cdf7603290232135f340e

2024-08-09 12:44 UTC, closed without merging